package com.southwind.odin.dal.mybatis.mapper;

import com.southwind.odin.dal.mybatis.model.News;
import com.southwind.odin.dal.mybatis.model.NewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    News selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Wed Jul 30 17:39:34 GMT+08:00 2014
     */
    int updateByPrimaryKey(News record);
}